name: Encode Base64 string
on:
  push:
    branches: [ main ]
jobs:
#  check_preconditions:
#    runs-on: ubuntu-latest
#    outputs:
#      results: ${{ join(steps.*.outcome) }}
#    steps:
#      - id: secrets_ssh
#        continue-on-error: true
#        env:
#          TOKEN: ${{ secrets.TOKEN_SECRET }}
#        run: '[ -n "$TOKEN_SECRET" ]'
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Retrieve the secret and decode it to a file
        env:
          STRING_BASE64: ${{ secrets.TOKEN_SECRET }}
        run: echo $STRING_BASE64 | base64 --decode
