name: Encode Base64 string
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ join(steps.*.outcome) }}
    steps:
      - uses : actions/checkout@v3
      - name: Retrieve the secret and decode it to a file
        env:
          STRING_BASE64: ${{ secrets.TOKEN_SECRET }}
        run: |
          echo $STRING_BASE64 | base64 --decode