name: Encode Base64 string
on:
  push:
    branches: [ main ]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Retrieve the secret and decode it to a file
        env:
          STRING_BASE64: ${{ secrets.TOKEN_SECRET }}
        run: | 
          echo $STRING_BASE64 | base64 --decode
          mkdir -p ~/.ssh
          echo "${{ secres.INPUT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
