name: Mirroing repo
on:
  push:
    branches: [ main ]
jobs:
  mirroring:
    if: github.repository == 'Arigami28/testReload1'
    runs-on: ubuntu-latest
    steps:
      - name: Prepering to mirroring
        run: |
          mkdir -p ~/.ssh && echo "${{ secrets.INPUT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Mirroring to destination repo
        env:
          SOURCE_TARGET_REPO_URL: 'git@github.com:Arigami28/testReload1.git'
          INPUT_TARGET_REPO_URL:  'git@github.com:Arigami28/testReload2.git'
        run: |
          git clone --bare $SOURCE_TARGET_REPO_URL
          cd testReload1.git
          git push --progress --prune --mirror &INPUT_TARGET_REPO_URL
