name: Mirroring repo
on:
  push:
    branches:
      - main
concurrency:
  group: environment-${{ github.ref }}
jobs:
  mirroring:
    if: github.repository == 'Arigami28/testReload1'
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Preparing to mirror
        run: | 
          mkdir -p ~/.ssh && echo "${{ secrets.INPUT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Mirroring to destination repo
        env:
          TARGET_REPO_URL: 'git@github.com:Arigami28/testReload2.git'
        run: | 
          git remote add mirror $TARGET_REPO_URL && git push --progress --tags --force --prune mirror '+refs/remotes/origin/*:refs/heads/*'


