name: Encode Base64 string
on:
  push:
    branches: [ main ]
jobs:
  check_preconditions:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ join(steps.*.outcome) }}
    steps:
      - id: secrets_ssh
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.TOKEN_SECRET }}
        run: '[ -n "$TOKEN_SECRET" ]'
  decode-secret:
    needs: check_preconditions
    if: "!contains(needs.check_preconditions.outputs.results, 'failure')"
    runs-on: ubuntu-latest
    outputs:
      results: ${{ join(steps.*.outcome) }}
    steps:
      - uses : actions/checkout@v3
      - name: Retrieve the secret and decode it to a file
        with:
          fetch-depth: 0
        env:
          STRING_BASE64: ${{ secrets_ssh.TOKEN }}
        run: echo $STRING_BASE64 | base64 --decode
